import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LayOutDefault from '@/components/LayOut/LayOutDefault'
import BoxContainer from '@/components/boxContainer/BoxContainer'
import BoxList from '@/components/boxList/BoxList'
import { CircularProgress } from '@mui/material'
import getListFilm from '@/api/getListFilm'
import * as React from 'react';
import getFilmNew from '@/api/getFilmNew'
import getFilmPopular from '@/api/getFilmPopular'
export interface Tag{
  id:string,
  name:string,
  thumbnail:string,
  slug?:string,
  soundtrack_count: number,
  author?:string,
  type?:number
}
function Container(){

  const [isLoading, setIsLoading] = React.useState(true);
  const [listFilm, setListFilm] = React.useState([]);
  const [listFilmPopular, setListFilmPopular] = React.useState([]); 

    const fetchDataFilm = async ()=>{
      const response = await getListFilm();
      if (response.status == 200) {
        setListFilm(response.data.data)
        setIsLoading(false)
      }
      
    }
    const fetchDataFilmPopular = async ()=>{
      const response = await getFilmPopular();
      if (response.status == 200) {
        setListFilmPopular(response.data.data)
        setIsLoading(false)
      }
      
    }

    React.useEffect(()=>{
      fetchDataFilm()
      fetchDataFilmPopular()
    },[])

    if (isLoading) {
      return (
        <CircularProgress />
      )
    }

  return (
    <div style={{
      width:"100%",
      minWidth:"300px",
      display:"flex",
      flexDirection:"column",
      alignContent:"center",
      justifyContent:"center",
      alignItems:"center",
      justifyItems:"center",
    }}>
      <BoxList ListItems={listFilm} title="List movies" type="movies"/>
      <BoxContainer isFilm={true} title="Hot movies" list={listFilmPopular}/>
    </div>
  )
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Popcorn Sound</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&display=swap" rel="stylesheet"/>
      </Head>
      <LayOutDefault child={<Container />} currentRoute="Movies"/>
    </div>
  )
}
